import { pgTable, serial, text, timestamp, integer, doublePrecision, boolean, bigint } from 'drizzle-orm/pg-core';

// 1. Users Table (synchronized with Firebase Auth UID)
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID
  email: text('email').notNull(),
  displayName: text('display_name'),
  photoUrl: text('photo_url'),
  createdAt: timestamp('created_at').defaultNow(),
});

// 2. Satellites Table (durable cloud storage for all registered CanSat & satellite nodes)
export const satellites = pgTable('satellites', {
  id: bigint('id', { mode: 'number' }).primaryKey(),
  satelliteId: text('satellite_id').notNull().unique(),
  collegeName: text('college_name').notNull(),
  studentName: text('student_name'),
  principalName: text('principal_name'),
  location: text('location').notNull(),
  weatherCondition: text('weather_condition'),
  aqi: integer('aqi'),
  temperature: doublePrecision('temperature'),
  humidity: doublePrecision('humidity'),
  pressure: doublePrecision('pressure'),
  windSpeed: doublePrecision('wind_speed'),
  batteryLevel: integer('battery_level'),
  rssi: integer('rssi'),
  orbitAltitude: integer('orbit_altitude'),
  lat: doublePrecision('lat').notNull(),
  lng: doublePrecision('lng').notNull(),
  isLiveStream: boolean('is_live_stream').default(true),
  lastPing: text('last_ping'),
  url: text('url'),
  childWebsiteUrl: text('child_website_url'),
  googleMapsUrl: text('google_maps_url'),
  appsScriptUrl: text('apps_script_url'),
  sourceType: text('source_type').default('standard'),
  isCustom: boolean('is_custom').default(true),
  studentPhoto: text('student_photo'),
  campusPhoto: text('campus_photo'),
  principalPhoto: text('principal_photo'),
  teacherPhoto: text('teacher_photo'),
  creatorUid: text('creator_uid'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// 3. Telemetry Packets Table (live sensor streaming history)
export const telemetryPackets = pgTable('telemetry_packets', {
  id: serial('id').primaryKey(),
  packetId: integer('packet_id'),
  satelliteId: text('satellite_id').notNull(),
  timestamp: text('timestamp'),
  epochMs: bigint('epoch_ms', { mode: 'number' }),
  hardwareId: text('hardware_id'),
  temperature: doublePrecision('temperature'),
  pressure: doublePrecision('pressure'),
  altitude: doublePrecision('altitude'),
  aqi: integer('aqi'),
  humidity: doublePrecision('humidity'),
  windSpeed: doublePrecision('wind_speed'),
  batteryVoltage: doublePrecision('battery_voltage'),
  batteryPercent: integer('battery_percent'),
  rssi: integer('rssi'),
  accelX: doublePrecision('accel_x'),
  accelY: doublePrecision('accel_y'),
  accelZ: doublePrecision('accel_z'),
  gyroX: doublePrecision('gyro_x'),
  gyroY: doublePrecision('gyro_y'),
  gyroZ: doublePrecision('gyro_z'),
  pitch: doublePrecision('pitch'),
  roll: doublePrecision('roll'),
  heading: doublePrecision('heading'),
  lat: doublePrecision('lat'),
  lng: doublePrecision('lng'),
  gpsFix: boolean('gps_fix').default(true),
  gpsStatus: text('gps_status'),
  gpsSats: integer('gps_sats'),
  hdop: doublePrecision('hdop'),
  savedToPenDrive: boolean('saved_to_pen_drive').default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// 4. Apps Script Data Sources Table
export const appsScriptSources = pgTable('apps_script_sources', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  satelliteId: text('satellite_id').notNull(),
  url: text('url').notNull(),
  childWebsiteUrl: text('child_website_url'),
  status: text('status').default('active'),
  lastPing: text('last_ping'),
  packetsCount: integer('packets_count').default(0),
  location: text('location'),
  principalName: text('principal_name'),
  studentName: text('student_name'),
  studentPhoto: text('student_photo'),
  autoLogToPenDrive: boolean('auto_log_to_pen_drive').default(true),
  lat: doublePrecision('lat'),
  lng: doublePrecision('lng'),
  googleMapsUrl: text('google_maps_url'),
  updatedAt: timestamp('updated_at').defaultNow(),
});
